// eslint-disable-next-line import/prefer-default-export
export function renderSearch() {
  const root = document.getElementById('root')
  root.innerHTML = '<div class="wrapper">\n'
    + '    <section class="section form">\n'
    + '        <h1 class="title-page">Weather Forecast</h1>\n'
    + '        <h2 class="title-description">Enter below your city or country:</h2>\n'
    + '        <form class="form-location">\n'
    + '            <fieldset class="form-fieldset">\n'
    + '                <label>\n'
    + '                    <input placeholder="Enter your city" class="form-input city" type="text" required>\n'
    + '                </label>\n'
    + '                <label>\n'
    + '                    <input placeholder="Enter your country" class="form-input country" type="text" required>\n'
    + '                </label>\n'
    + '            </fieldset>\n'
    + '            <button class="form-btn-submit">Submit</button>\n'
    + '        </form>\n'
    + '    </section>\n'
    + '    <section class="section weather hidden">\n'
    + '        <div class="weather-info"></div>\n'
    + '        <div class="weather-icon"></div>\n'
    + '        <div class="weather-temperature"></div>\n'
    + '        <div class="weather-location"></div>\n'
    + '        <div class="weather-parameters">\n'
    + '            <div class="param time"></div>\n'
    + '            <div class="param wind"></div>\n'
    + '            <div class="param feels-like"></div>\n'
    + '            <div class="param speed"></div>\n'
    + '            <div class="param today-is"></div>\n'
    + '            <div class="param pressure"></div>\n'
    + '        </div>\n'
    + '    </section>\n'
    + '</div>'
}
